#! /usr/bin/env Rscript --vanilla
if(!require(renv)) {install.packages("renv",repos="http://cran.us.r-project.org")}
library(renv)
renv::activate()
renv::init(bare=T)
renv::isolate()
renv::settings$snapshot.type("all")
renv::install("rmarkdown")
renv::install("devtools")
install.packages("BiocManager")
BiocManager::install(version = "3.12", ask=FALSE)
BiocManager::repositories(version="3.12")
renv::install("remotes")
renv::install("jbisanz/qiime2R@d1ad96657ada993cf6c2841b29113a4f635c6b56", rebuild=TRUE)
renv::snapshot()
q()
