---
title: "01 16s Analysis Report"
output:
  pdf_document:
    df_print: kable
  html_document:
    df_print: kable
    smart: false
---

```{r init renv, message=FALSE, warning=FALSE, include=FALSE}
library(renv)
#renv::isolate()
#renv::settings$snapshot.type("all")
renv::restore()
```



```{r parse item of interest and make outdir for figures, echo=FALSE, message=FALSE, warning=FALSE}
#this may be required for each file
#item of interest, comes from bash and python script that orchestrates everything
wd <- getwd()
ioi <- read.csv("../item_of_interest.csv")
ioi<-as.character(ioi)

ioi_ord <- read.csv("../order_item_of_interest.csv")
colnames(ioi_ord) <- ioi
ioi_ord <- as.list(ioi_ord)[[ioi]]

outdir_name <- "Figures"
if(!dir.exists(paste0("../",outdir_name))) {dir.create(paste0("../",outdir_name))}
outdir <- paste0("../",outdir_name)
```

## 1 Species Distribution 

### 1.1 Relative Abundance of Top 10 Phyla

```{r stacked bar chart at Phylum level, echo=FALSE, fig.height=12, fig.width=18, message=FALSE, warning=FALSE}
#TODO add library calls
library(qiime2R)
library(phyloseq)
library(ggplot2)
library(tidyverse)

options(bitmapType='cairo')
level = "Phylum"

#table_dada2 <- "../qiime/table-dada2.qza"
table_dada2 <- "../qiime/core-metric-results/rarefied_table.qza"
rooted_tree <- "../qiime/rooted-tree.qza"
taxonomy_file <- "../qiime/taxonomy.qza"
metadata_file <- "../metadata.tsv"


#Create phyloseq object from qiime objects
cycle_1 <- qza_to_phyloseq(table_dada2,rooted_tree,taxonomy_file,metadata_file)

#from https://github.com/joey711/phyloseq/issues/850#issuecomment-394771087
tax.clean <- data.frame(tax_table(cycle_1))

for (i in 1:7){ tax.clean[,i] <- as.character(tax.clean[,i])}

tax.clean[is.na(tax.clean)] <- ""

for (i in 1:nrow(tax.clean)){
if (tax.clean[i,2] == ""){
kingdom <- paste("Kingdom_", tax.clean[i,1], sep = "")
tax.clean[i, 2:7] <- kingdom
} else if (tax.clean[i,3] == ""){
phylum <- paste("Phylum_", tax.clean[i,2], sep = "")
tax.clean[i, 3:7] <- phylum
} else if (tax.clean[i,4] == ""){
class <- paste("Class_", tax.clean[i,3], sep = "")
tax.clean[i, 4:7] <- class
} else if (tax.clean[i,5] == ""){
order <- paste("Order_", tax.clean[i,4], sep = "")
tax.clean[i, 5:7] <- order
} else if (tax.clean[i,6] == ""){
family <- paste("Family_", tax.clean[i,5], sep = "")
tax.clean[i, 6:7] <- family
} else if (tax.clean[i,7] == ""){
tax.clean$Species[i] <- paste("Genus",tax.clean$Genus[i], sep = "_")
}
}

tax_table(cycle_1) <- as.matrix(tax.clean)

#Select number of taxa at phylum level to plot
topN <- 10

cycle_n_names <- sort(tapply(taxa_sums(cycle_1), tax_table(cycle_1)[,as.character(level)], sum), TRUE) [1:topN]


if (length(as.vector(na.exclude(names(cycle_n_names)))) <= topN){
  topN <- length(as.vector(na.exclude(names(cycle_n_names))))
  #selects top n taxa and creates phyloseq object
  cycle_n <- subset_taxa(cycle_1, get(level) %in% as.vector(na.exclude(names(cycle_n_names))))
  cycle_n_glom <- tax_glom(cycle_n, taxrank = level)

  #calculates relative abundance based on sample provided and turns that into a dataframe for ggplot2 plotting
  cycle_1_phylum <- cycle_n %>%
    tax_glom(taxrank = level) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)


  #ggplot2 stacked bar chart separated by sample in the metadata from qiime2
  by_sample <- ggplot(cycle_1_phylum, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cycle_1_phylum[[level]], Abundance),"Other"))) +
    geom_bar(stat= "identity") +
    xlab("Sample ID") +
    ylab(label="Relative Abundance") +
    guides(fill=guide_legend(title=level))+
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90,vjust=0.5, hjust=1))+
    theme(text=element_text(size = 20))

  print(by_sample)
  ggsave("stacked_bar_phylum_by_sample.png", plot=by_sample, path=outdir)

  #calculates relative abundance based on item of interest provided in original bash script
  cy_phylum <- cycle_n %>%
    tax_glom(taxrank = level) %>%
    merge_samples(ioi,fun=sum) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)

  cy_phylum$Sample <- factor(cy_phylum$Sample, levels=ioi_ord)

  #ggplot2 stacked bar chart separated by item of interet in the metadata from qiime2 identified by user
  by_treatment <- ggplot(cy_phylum, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cy_phylum[[level]],Abundance),"Other"))) +
    geom_bar(stat="identity") +
    guides(fill=guide_legend(title=level)) +
    xlab(label = ioi) +
    ylab(label="Relative Abundance") +
    theme_minimal()+
    theme(text=element_text(size = 20))


  #prints charts to rnotebook

  print(by_treatment)

  #saves charts to directory

  ggsave("stacked_bar_phylum_by_treatment.png", plot=by_treatment, path=outdir)
} else {
    #selects top n taxa and creates phyloseq object
  cycle_n <- subset_taxa(cycle_1, get(level) %in% as.vector(na.exclude(names(cycle_n_names))))
  cycle_n_glom <- tax_glom(cycle_n, taxrank = level)

  #selects top n + 1 to the end of table
  rest_tax <- sort(tapply(taxa_sums(cycle_1), tax_table(cycle_1)[,as.character(level)], sum), TRUE)[topN+1:length(tax_table(cycle_1))]
  rest <- subset_taxa(cycle_1, get(level) %in% as.vector(na.exclude(names(rest_tax))))
  rest_glom <- tax_glom(rest, taxrank = level)

  #collapse all phyla not in top 10 into one taxon
  rest_merge <- merge_taxa(rest, taxa_names(rest))

  #create dummy taxonomy classification for collapsed taxa
  taxvec <- c("Other","Other","Other","Other","Other", "Other","Other")
  taxlist <- list(OTU1=parse_taxonomy_default(taxvec))
  tax_tab <- build_tax_table(taxlist)
  colnames(tax_tab) <- c("Kingdom","Phylum","Class","Order","Family","Genus","Species")
  rownames(tax_tab) <- rownames(tax_table(rest_merge))
  tax_table(rest_merge) <- tax_tab

  #attaches top n phyloseq object with the other phyloseq object
  merge_tax <- merge_phyloseq(tax_table(cycle_n), tax_table(rest_merge))
  merge_otu <- merge_phyloseq(otu_table(cycle_n), otu_table(rest_merge))
  merge_samp <- merge_phyloseq(sample_data(cycle_n), sample_data(rest_merge))

  merged <- merge_phyloseq(merge_tax, merge_otu, merge_samp)

  #calculates relative abundance based on sample provided and turns that into a dataframe for ggplot2 plotting
  cycle_1_phylum <- merged %>%
    tax_glom(taxrank = level) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)


  #ggplot2 stacked bar chart separated by sample in the metadata from qiime2
  by_sample <- ggplot(cycle_1_phylum, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cycle_1_phylum[[level]], Abundance),"Other"))) +
    geom_bar(stat= "identity") +
    xlab("Sample ID") +
    ylab(label="Relative Abundance") +
    guides(fill=guide_legend(title=level))+
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90,vjust=0.5, hjust=1))+
    theme(text=element_text(size = 20))

  print(by_sample)
  ggsave("stacked_bar_phylum_by_sample.png", plot=by_sample, path=outdir)

  #calculates relative abundance based on item of interest provided in original bash script
  cy_phylum <- merged %>%
    tax_glom(taxrank = level) %>%
    merge_samples(ioi,fun=sum) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)

  cy_phylum$Sample <- factor(cy_phylum$Sample, levels=ioi_ord)

  #ggplot2 stacked bar chart separated by item of interet in the metadata from qiime2 identified by user
  by_treatment <- ggplot(cy_phylum, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cy_phylum[[level]],Abundance),"Other"))) +
    geom_bar(stat="identity") +
    guides(fill=guide_legend(title=level)) +
    xlab(label = ioi) +
    ylab(label="Relative Abundance") +
    theme_minimal()+
    theme(text=element_text(size = 20))


  #prints charts to rnotebook

  print(by_treatment)

  #saves charts to directory

  ggsave("stacked_bar_phylum_by_treatment.png", plot=by_treatment, path=outdir)
}
```

### 1.2 Relative Abundance of Top 10 Genera

```{r stacked bar chart at Genus level, echo=FALSE, fig.height=12, fig.width=18, message=FALSE, warning=FALSE}
library(qiime2R)
library(phyloseq)
library(ggplot2)

level = "Genus"

#Create phyloseq object from qiime objects
cycle_1 <- qza_to_phyloseq(table_dada2,rooted_tree,taxonomy_file,metadata_file)

#from https://github.com/joey711/phyloseq/issues/850#issuecomment-394771087
tax.clean <- data.frame(tax_table(cycle_1))

for (i in 1:7){ tax.clean[,i] <- as.character(tax.clean[,i])}

tax.clean[is.na(tax.clean)] <- ""

for (i in 1:nrow(tax.clean)){
if (tax.clean[i,2] == ""){
kingdom <- paste("Kingdom_", tax.clean[i,1], sep = "")
tax.clean[i, 2:7] <- kingdom
} else if (tax.clean[i,3] == ""){
phylum <- paste("Phylum_", tax.clean[i,2], sep = "")
tax.clean[i, 3:7] <- phylum
} else if (tax.clean[i,4] == ""){
class <- paste("Class_", tax.clean[i,3], sep = "")
tax.clean[i, 4:7] <- class
} else if (tax.clean[i,5] == ""){
order <- paste("Order_", tax.clean[i,4], sep = "")
tax.clean[i, 5:7] <- order
} else if (tax.clean[i,6] == ""){
family <- paste("Family_", tax.clean[i,5], sep = "")
tax.clean[i, 6:7] <- family
} else if (tax.clean[i,7] == ""){
tax.clean$Species[i] <- paste("Genus",tax.clean$Genus[i], sep = "_")
}
}

tax_table(cycle_1) <- as.matrix(tax.clean)


#Select number of taxa at genus level to plot
topN <- 10

cycle_n_names <- sort(tapply(taxa_sums(cycle_1), tax_table(cycle_1)[,as.character(level)], sum), TRUE) [1:topN]

if (length(as.vector(na.exclude(names(cycle_n_names)))) <= topN){
  #selects top n taxa and creates phyloseq object
  cycle_n <- subset_taxa(cycle_1, get(level) %in% as.vector(na.exclude(names(cycle_n_names))))
  cycle_n_glom <- tax_glom(cycle_n, taxrank = level)

  #calculate relative abundance based on sample
  cycle_1_genus <- cycle_n %>%
    tax_glom(taxrank = level) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)

  #ggplot of stacked bar chart separated by sample
  by_sample <- ggplot(cycle_1_genus, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cycle_1_genus[[level]], Abundance),"Other"))) + 
    geom_bar(stat= "identity") +
    xlab("Sample ID") +
    ylab(label="Relative Abundance") +
    guides(fill=guide_legend(title=level))+
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90,vjust=0.5, hjust=1)) +
    theme(text=element_text(size = 20))

  print(by_sample)
  ggsave("stacked_bar_genus_by_sample.png", plot=by_sample, path=outdir)

  #calculate relative abundance based on treatment 
  cy_genus <- cycle_n %>%
    tax_glom(taxrank = level) %>%
    merge_samples(ioi,fun=sum) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)

  cy_genus$Sample <- factor(cy_genus$Sample, levels=ioi_ord)

  #ggplot figure of stacked bar chart separated by treatment
  by_treatment <- ggplot(cy_genus, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cy_genus[[level]],Abundance),"Other"))) + 
    geom_bar(stat="identity") +
    guides(fill=guide_legend(title=level)) + 
    xlab(label = ioi) +
    ylab(label="Relative Abundance") +
    theme_minimal()+
    theme(text=element_text(size = 20))

  #prints charts for rnotebook

  print(by_treatment)

  #saves copies of figures to outdir

  ggsave("stacked_bar_genus_by_treatment.png", plot = by_treatment, path=outdir)

}else{
  #selects top n taxa and creates phyloseq object
  cycle_n <- subset_taxa(cycle_1, get(level) %in% as.vector(na.exclude(names(cycle_n_names))))
  cycle_n_glom <- tax_glom(cycle_n, taxrank = level)

  #selects top n + 1 to the end of table
  rest_tax <- sort(tapply(taxa_sums(cycle_1), tax_table(cycle_1)[,as.character(level)], sum), TRUE) [topN+1:length(tax_table(cycle_1))]
  rest <- subset_taxa(cycle_1, get(level) %in% as.vector(na.exclude(names(rest_tax))))
  rest_glom <- tax_glom(rest, taxrank = level)

  #collapse all genera not in top 10 into one taxon
  rest_merge <- merge_taxa(rest, taxa_names(rest))

  #create dummy taxonomy classificaiton for collapsed taxa
  taxvec <- c("Other","Other","Other","Other","Other", "Other","Other")
  taxlist <- list(OTU1=parse_taxonomy_default(taxvec))
  tax_tab <- build_tax_table(taxlist)
  colnames(tax_tab) <- c("Kingdom","Phylum","Class","Order","Family","Genus","Species")
  rownames(tax_tab) <- rownames(tax_table(rest_merge))
  tax_table(rest_merge) <- tax_tab

  #attaches top n phyloseq object with the other phyloseq object
  merge_tax <- merge_phyloseq(tax_table(cycle_n), tax_table(rest_merge))
  merge_otu <- merge_phyloseq(otu_table(cycle_n), otu_table(rest_merge))
  merge_samp <- merge_phyloseq(sample_data(cycle_n), sample_data(rest_merge))

  merged <- merge_phyloseq(merge_tax, merge_otu, merge_samp)

    #calculate relative abundance based on sample
  cycle_1_genus <- merged %>%
    tax_glom(taxrank = level) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)

  #ggplot of stacked bar chart separated by sample
  by_sample <- ggplot(cycle_1_genus, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cycle_1_genus[[level]], Abundance),"Other"))) + 
    geom_bar(stat= "identity") +
    xlab("Sample ID") +
    ylab(label="Relative Abundance") +
    guides(fill=guide_legend(title=level))+
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90,vjust=0.5, hjust=1)) +
    theme(text=element_text(size = 20))

  print(by_sample)
  ggsave("stacked_bar_genus_by_sample.png", plot=by_sample, path=outdir)

  #calculate relative abundance based on treatment 
  cy_genus <- merged %>%
    tax_glom(taxrank = level) %>%
    merge_samples(ioi,fun=sum) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)

  cy_genus$Sample <- factor(cy_genus$Sample, levels=ioi_ord)

  #ggplot figure of stacked bar chart separated by treatment
  by_treatment <- ggplot(cy_genus, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cy_genus[[level]],Abundance),"Other"))) + 
    geom_bar(stat="identity") +
    guides(fill=guide_legend(title=level)) + 
    xlab(label = ioi) +
    ylab(label="Relative Abundance") +
    theme_minimal()+
    theme(text=element_text(size = 20))

  #prints charts for rnotebook

  print(by_treatment)

  #saves copies of figures to outdir

  ggsave("stacked_bar_genus_by_treatment.png", plot = by_treatment, path=outdir)
}
```


### 1.3 Relative Abundance of Top 10 Species

```{r stacked bar chart at Species level, echo=FALSE, fig.height=12, fig.width=18, message=FALSE, warning=FALSE}
library(qiime2R)
library(phyloseq)
library(ggplot2)
library(tidyverse)

level = "Species"

#Create phyloseq object from qiime objects
cycle_1 <- qza_to_phyloseq(table_dada2,rooted_tree,taxonomy_file,metadata_file)

#from https://github.com/joey711/phyloseq/issues/850#issuecomment-394771087
tax.clean <- data.frame(tax_table(cycle_1))

for (i in 1:7){ tax.clean[,i] <- as.character(tax.clean[,i])}

tax.clean[is.na(tax.clean)] <- ""

for (i in 1:nrow(tax.clean)){
if (tax.clean[i,2] == ""){
kingdom <- paste("Kingdom_", tax.clean[i,1], sep = "")
tax.clean[i, 2:7] <- kingdom
} else if (tax.clean[i,3] == ""){
phylum <- paste("Phylum_", tax.clean[i,2], sep = "")
tax.clean[i, 3:7] <- phylum
} else if (tax.clean[i,4] == ""){
class <- paste("Class_", tax.clean[i,3], sep = "")
tax.clean[i, 4:7] <- class
} else if (tax.clean[i,5] == ""){
order <- paste("Order_", tax.clean[i,4], sep = "")
tax.clean[i, 5:7] <- order
} else if (tax.clean[i,6] == ""){
family <- paste("Family_", tax.clean[i,5], sep = "")
tax.clean[i, 6:7] <- family
} else if (tax.clean[i,7] == ""){
tax.clean$Species[i] <- paste("Genus",tax.clean$Genus[i], sep = "_")
}
}

tax_table(cycle_1) <- as.matrix(tax.clean)

#Select number of taxa at species level to plot
topN <- 10

cycle_n_names <- sort(tapply(taxa_sums(cycle_1), tax_table(cycle_1)[,as.character(level)], sum), TRUE) [1:topN]


if (length(as.vector(na.exclude(names(cycle_n_names)))) <= topN){
  topN <- length(as.vector(na.exclude(names(cycle_n_names))))
  #selects top n taxa and creates phyloseq object
  cycle_n <- subset_taxa(cycle_1, get(level) %in% as.vector(na.exclude(names(cycle_n_names))))
  cycle_n_glom <- tax_glom(cycle_n, taxrank = level)

  #calculates relative abundance based on sample provided and turns that into a dataframe for ggplot2 plotting
  cycle_1_phylum <- cycle_n %>%
    tax_glom(taxrank = level) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)


  #ggplot2 stacked bar chart separated by sample in the metadata from qiime2
  by_sample <- ggplot(cycle_1_phylum, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cycle_1_phylum[[level]], Abundance),"Other"))) +
    geom_bar(stat= "identity") +
    xlab("Sample ID") +
    ylab(label="Relative Abundance") +
    guides(fill=guide_legend(title=level))+
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90,vjust=0.5, hjust=1))+
    theme(text=element_text(size = 20))

  print(by_sample)
  ggsave("stacked_bar_species_by_sample.png", plot=by_sample, path=outdir)

  #calculates relative abundance based on item of interest provided in original bash script
  cy_phylum <- cycle_n %>%
    tax_glom(taxrank = level) %>%
    merge_samples(ioi,fun=sum) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)

  cy_phylum$Sample <- factor(cy_phylum$Sample, levels=ioi_ord)

  #ggplot2 stacked bar chart separated by item of interet in the metadata from qiime2 identified by user
  by_treatment <- ggplot(cy_phylum, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cy_phylum[[level]],Abundance),"Other"))) +
    geom_bar(stat="identity") +
    guides(fill=guide_legend(title=level)) +
    xlab(label = ioi) +
    ylab(label="Relative Abundance") +
    theme_minimal()+
    theme(text=element_text(size = 20))


  #prints charts to rnotebook

  print(by_treatment)

  #saves charts to directory

  ggsave("stacked_bar_species_by_treatment.png", plot=by_treatment, path=outdir)
} else {
    #selects top n taxa and creates phyloseq object
  cycle_n <- subset_taxa(cycle_1, get(level) %in% as.vector(na.exclude(names(cycle_n_names))))
  cycle_n_glom <- tax_glom(cycle_n, taxrank = level)

  #selects top n + 1 to the end of table
  rest_tax <- sort(tapply(taxa_sums(cycle_1), tax_table(cycle_1)[,as.character(level)], sum), TRUE)[topN+1:length(tax_table(cycle_1))]
  rest <- subset_taxa(cycle_1, get(level) %in% as.vector(na.exclude(names(rest_tax))))
  rest_glom <- tax_glom(rest, taxrank = level)

  #collapse all phyla not in top 10 into one taxon
  rest_merge <- merge_taxa(rest, taxa_names(rest))

  #create dummy taxonomy classification for collapsed taxa
  taxvec <- c("Other","Other","Other","Other","Other", "Other","Other")
  taxlist <- list(OTU1=parse_taxonomy_default(taxvec))
  tax_tab <- build_tax_table(taxlist)
  colnames(tax_tab) <- c("Kingdom","Phylum","Class","Order","Family","Genus","Species")
  rownames(tax_tab) <- rownames(tax_table(rest_merge))
  tax_table(rest_merge) <- tax_tab

  #attaches top n phyloseq object with the other phyloseq object
  merge_tax <- merge_phyloseq(tax_table(cycle_n), tax_table(rest_merge))
  merge_otu <- merge_phyloseq(otu_table(cycle_n), otu_table(rest_merge))
  merge_samp <- merge_phyloseq(sample_data(cycle_n), sample_data(rest_merge))

  merged <- merge_phyloseq(merge_tax, merge_otu, merge_samp)

  #calculates relative abundance based on sample provided and turns that into a dataframe for ggplot2 plotting
  cycle_1_phylum <- merged %>%
    tax_glom(taxrank = level) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)


  #ggplot2 stacked bar chart separated by sample in the metadata from qiime2
  by_sample <- ggplot(cycle_1_phylum, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cycle_1_phylum[[level]], Abundance),"Other"))) +
    geom_bar(stat= "identity") +
    xlab("Sample ID") +
    ylab(label="Relative Abundance") +
    guides(fill=guide_legend(title=level))+
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90,vjust=0.5, hjust=1))+
    theme(text=element_text(size = 20))

  print(by_sample)
  ggsave("stacked_bar_species_by_sample.png", plot=by_sample, path=outdir)

  #calculates relative abundance based on item of interest provided in original bash script
  cy_phylum <- merged %>%
    tax_glom(taxrank = level) %>%
    merge_samples(ioi,fun=sum) %>%
    transform_sample_counts(function(x) {x/sum(x)}) %>%
    psmelt() %>%
    arrange(Abundance)

  cy_phylum$Sample <- factor(cy_phylum$Sample, levels=ioi_ord)

  #ggplot2 stacked bar chart separated by item of interet in the metadata from qiime2 identified by user
  by_treatment <- ggplot(cy_phylum, aes(x=Sample, y=Abundance, fill=fct_relevel(fct_reorder(cy_phylum[[level]],Abundance),"Other"))) +
    geom_bar(stat="identity") +
    guides(fill=guide_legend(title=level)) +
    xlab(label = ioi) +
    ylab(label="Relative Abundance") +
    theme_minimal()+
    theme(text=element_text(size = 20))


  #prints charts to rnotebook

  print(by_treatment)

  #saves charts to directory

  ggsave("stacked_bar_species_by_treatment.png", plot=by_treatment, path=outdir)
}

```

