---
title: "05 16s Analysis Report"
output:
  pdf_document:
    
    
    df_print: kable
  html_document:
    df_print: kable
    smart: false
---

```{r init renv, message=FALSE, warning=FALSE, include=FALSE}
library(renv)
#renv::isolate()
#renv::settings$snapshot.type("all")
renv::restore()
```

```{r parse item of interest and make outdir for figures, echo=FALSE, message=FALSE, warning=FALSE}
#this may be required for each file
#item of interest, comes from bash and python script that orchestrates everything
wd <- getwd()
ioi <- read.csv("../item_of_interest.csv")
ioi<-as.character(ioi)

ioi_ord <- read.csv("../order_item_of_interest.csv")
colnames(ioi_ord) <- ioi
ioi_ord <- as.list(ioi_ord)[[ioi]]

outdir_name <- "Figures"
if(!dir.exists(paste0("./",outdir_name))) {dir.create(paste0("./",outdir_name))}
outdir <- paste0("./",outdir_name)

# library(tidyverse)
# library(reshape2)
# library(dplyr)
# library(ggplot2)
```

## 8 Ranked Abundance Curves

```{r, echo=FALSE, fig.height=10, fig.width=16, message=FALSE, warning=FALSE}
#library(devtools)
#llibrary(remotes)
#install.packages("BiocManager")
#BiocManager::install(version="3.13")
library(ampvis2)
#b655a307c8431201573096ab57140b46d8733dd7
library(ggplot2)
library(qiime2R)
#d1ad96657ada993cf6c2841b29113a4f635c6b56
library(phyloseq)
library(tidyverse)
#@1.3.1

#table_dada2 <- "./qiime/table-dada2.qza"
table_dada2 <- "../qiime/core-metric-results/rarefied_table.qza"
rooted_tree <- "../qiime/rooted-tree.qza"
taxonomy_file <- "../qiime/taxonomy.qza"
metadata_file <- "../metadata.tsv"

devtools::source_gist("8d0ca4206a66be7ff6d76fc4ab8e66c6")

cycle_1 <- qza_to_phyloseq(table_dada2,rooted_tree,taxonomy_file,metadata_file) 
cycle_1_amp <- phyloseq_to_ampvis2(cycle_1)

by_sample <- ampvis2::amp_rankabundance(cycle_1_amp, group_by = "SampleID") + theme(text=element_text(size = 20), legend.position="none")
by_sample 
ggsave("rank_abundance_curve_by_sample.png", plot=by_sample, path=outdir)

cycle_1_amp$metadata[[ioi]] <- factor(cycle_1_amp$metadata[[ioi]], levels=ioi_ord)

by_group <- ampvis2::amp_rankabundance(cycle_1_amp, group_by = ioi) + theme(text=element_text(size = 20))
by_group
ggsave("rank_abundance_curve_by_treatemnt.png", plot=by_group, path=outdir)
```