---
title: "04 16s Analysis Report"
output:
  pdf_document:
    df_print: kable
  html_document:
    df_print: kable
    smart: false
---

```{r init renv, message=FALSE, warning=FALSE, include=FALSE}
#library(renv)
#renv::isolate()
#renv::settings$snapshot.type("all")
#renv::restore()
```

```{r parse item of interest and make outdir for figures, echo=FALSE, message=FALSE, warning=FALSE}
#this may be required for each file
#item of interest, comes from bash and python script that orchestrates everything
wd <- getwd()
ioi <- readLines("item_of_interest.csv")
ioi<-as.character(ioi)

ioi_ord <- read.csv("order_item_of_interest.csv")
colnames(ioi_ord) <- ioi
ioi_ord <- as.list(ioi_ord)[[ioi]]

outdir_name <- "Figures"
if(!dir.exists(outdir_name)) {dir.create(outdir_name)}
outdir <- outdir_name
```



## 4 Alpha Diversity Table

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(kableExtra)
library(tidyverse)

obs <- read.table("obs/metadata.tsv", header = TRUE)
shannon <- read.table("shannon/metadata.tsv", header = TRUE)
simpson <- read.table("simpson/metadata.tsv", header=TRUE)
chao1 <- read.table("chao1/metadata.tsv", header=TRUE)
ace <- read.table("ace/metadata.tsv", header=TRUE)
faith_pd <- read.table("faith_pd/metadata.tsv", header=TRUE)

obs <- data.frame(obs[c('id','observed_features')])
shannon <- data.frame(shannon[c('id','shannon_entropy')])
simpson <- data.frame(simpson[c('id','simpson')])
chao1 <- data.frame(chao1[c('id','chao1')])
ace <- data.frame(ace[c("id","ace")])
faith_pd <- data.frame(faith_pd[c("id","faith_pd")])

alpha_summary <- Reduce(function(...) merge(..., by='id', all.x=TRUE), list(obs,shannon,simpson,chao1,ace,faith_pd))
kable(alpha_summary) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

